version: '3.9'
services:
  db:
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env.development
    ports:
      - 5432:5432
    volumes:
      - pg-volume:/var/lib/postgresql/data/
  redis:
    image: 'redis:alpine'
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - '6379:6379'
    env_file:
      - .env.development
    volumes:
      - redis-volume:/data
volumes:
  pg-volume:
  redis-volume:
